### ISSUE TITLE
Why "SA-cim_validator" app is not loading my "raw/datamodels" in "Target datamodel", any possible reasons or troubleshooting help ?

### ISSUE THREAD

**Issue by Rakesh597** [hire-vladimir/SA-cim_validator#14]
[https://answers.splunk.com/answers/629476/why-sa-cim-validator-app-is-not-loading-my-rawdata.html](url)

**Comment by hire-vladimir** [comment]
if you are looking to validate agains Splunk developed datamodels, part of Common Information Model, you need to install Splunk_SA_CIM, see https://splunkbase.splunk.com/app/1621/ Otherwise, you will need to create your own datamodel definitions to validate against.
