### ISSUE TITLE
date field should contain a date without time

### ISSUE THREAD

**Issue by ghost** [hire-vladimir/SA-cim_validator#7]

**Comment by hire-vladimir** [comment]
the Malware DM, which is the only DM with a date field, defines date as `strftime(_time, "%m-%d-%Y")`, hence the regex should probably be `^\d{2}-\d{2}-\d{4}$`

**Comment by ghost** [comment]
I see your point
probably be best to use ^[01][0-9]-[0123][0-9]-[12]\d{3}$

**Comment by hire-vladimir** [comment]
that works, do a pull request with that change
